name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: DDD_COURSEWORK

    - name: Build solution
      run: dotnet build --configuration Release
      working-directory: DDD_COURSEWORK

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal
      working-directory: DDD_COURSEWORK
